#define desc "This is a simple open-sorced script generator that let you generate script that can start a customization cmd."
#define author "jaydensc-tsk on github"
#define license "MIT license"
#define version "WINOSREL_1.0.2_26024"
#define update "2026-02-24"
#define build "26204"
#define project_name "cmd-customization-gen"
#define init_executable_name "cmd-gen.exe"
#define usage "copy the script below and paste it in a text file,then change the file name to [NAME].bat,the [NAME] can be any string"